### ISSUE TITLE
Task running not display ticket

### ISSUE THREAD

**Issue by alexandreti2018** [ticgal/actualtime#104]
it is not possible to start a new task because the system informs that a task is already running. but it does not show the ticket number.

glpi 10.0.2
plugin 2.0.0

**Comment by gitsyncuser** [comment]
<p>Hi,</p>\r\n<p>This was probably caused because you deleted a task or probably the whole ticket while the AcualTime was running.</p>\r\n<p>This is a really terrible practice. You need to delete the record on the DB.</p>\r\n<p>Regards,</p><blockquote>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Óscar Beiro</blockquote>

**Comment by guinfox** [comment]
'm having the same problem, how can I solve it, I don't know how I could remove the registry, could anyone help me?
![image](https://user-images.githubusercontent.com/107438460/194376378-ed660060-a1b0-4427-ad5e-9bb65e8769bc.png)

**Comment by alexandreti2018** [comment]
which database table can I query to see if there are any tasks running?

**Comment by andersonrmartins** [comment]
Estou com o mesmo problema, qual tabela devemos pesquisar ?

**Comment by alexandreti2018** [comment]
após excluir o linha na tabela  glpi_plugin_actualtime_tasks o problema foi resolvido. Mas precisamos que seja corrigido na próxima versão do plugin para identificar o chamado e corrigir direto no GLPI.

**Comment by andersonrmartins** [comment]
Desenvolvi uma Query para puxar relatório de apontamento de horas, seria muito bom se ele estivesse integrado ao Plugin 
pois quem trabalha com Apontamento de Horas, provavelmente necessita de um relatório para verificar os apontamentos.
Se estiver interesse, gostaria de colaborar fornecendo a query para a implantação nas próximas versões
----
I developed a Query to pull a time report, it would be great if it were integrated into the Plugin
because whoever works with Hours, probably needs a report to verify the notes.
If you are interested, I would like to collaborate by providing the query for deployment in the next versions

**Comment by guinfox** [comment]
Very good, could you share with us?



Em sex., 2 de dez. de 2022 às 14:59, andersonrmartins <
***@***.***> escreveu:

**Comment by andersonrmartins** [comment]
@guinfox 

SELECT gt.id CHAMADO,ge.name CLIENTE,
COALESCE(CONCAT(gu2.firstname,' ',gu2.realname),gtu.alternative_email) SOLICITANTE,
COALESCE(CONCAT(gu.firstname," ",gu.realname),CONCAT(gu3.firstname," ",gu3.realname)) CONSULTOR,
gt.name SOLICITACAO,
REPLACE(REPLACE(gt.content,"&#60;p&#62;",""),"&#60;/p&#62;","") CONTEUDO,
REPLACE(REPLACE(gt2.content,"&#60;p&#62;",""),"&#60;/p&#62;","") REALIZADO,
DATE_FORMAT(TIMESTAMP(gt2.date_creation),'%Y-%m-%d %H:%i:%s') as Date,
COALESCE(gpat.actual_end,gt.closedate,'CHAMADO ABERTO') FIM,
SEC_TO_TIME(COALESCE(gpat.actual_actiontime,0)) TOTAL,
SEC_TO_TIME (COALESCE(gt2.actiontime,0)) MANUAL,
SEC_TO_TIME(COALESCE(gpat.actual_actiontime,0)+COALESCE(gt2.actiontime,0)) GERAL
FROM glpi_tickets gt 
LEFT JOIN glpi_tickettasks gt2 ON gt2.tickets_id = gt.id 
LEFT JOIN glpi_plugin_actualtime_tasks gpat ON gpat.tickettasks_id = gt2.id
LEFT JOIN glpi_entities ge ON gt.entities_id = ge.id 
LEFT JOIN glpi_users gu ON gu.id = gpat.users_id 
LEFT JOIN glpi_users gu2 ON gu2.id = gt.users_id_recipient
LEFT JOIN glpi_users gu3 ON gu3.id = gt2.users_id 
LEFT JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id and gtu.`type` ='1'
WHERE REPLACE(REPLACE(gt2.content,"&#60;p&#62;",""),"&#60;/p&#62;","") IS NOT NULL

**Comment by OscarBeiro** [comment]
New ActualTime release, disallows some other scenarios like this one, to avoid issues when bad practices are applied.
