### ISSUE TITLE
 Start counter in pre-categorized tasks in task categories

### ISSUE THREAD

**Issue by isacporter** [ticgal/actualtime#49]
Start counter in pre-categorized tasks in task categories.
When the pre-categorized task is selected, the counter option is not displayed. 

Glpi 9.4.2
Actualtime: 1.2.0

![image](https://user-images.githubusercontent.com/32395226/61549351-2bb0d880-aa26-11e9-863c-570aebe5c7ff.png)

**Comment by OscarBeiro** [comment]
Olá Isac, :)

The counter will only be displayed if:


1. A user is assigned to the ticket task.

1. The assigned user opens the task

None of the two conditions are met in your screenshot.

Cumprimentos

**Comment by Phorta** [comment]
@OscarBeiro
The button only appears when the call is directed to a specific user.
Would you like to appear if the task is directed to a technical group?

I ask this because I work with preventive maintenance Tickets and we use a lot of recurring tickets function along with ticket templates.
With this I direct the call always to the technical group, because I do not know in advance which the technician will be available to answer the call.

Ideally, the buttons would appear without the need to have a person or group allocated the task, as the technician will already be responding to the ticket

**Comment by OscarBeiro** [comment]
Hi @Phorta 

I see your point, but we have conceived this ticket to track techs time. A task tech is compulsory, 
The tech who steals or takes the task into consideration, must be added to the task to track its own time.

Tracking group time makes no sense IMHO.

If you still think this feature is needed please contact us to consider a custom development.
Regards,

**Comment by Phorta** [comment]
Hi Oscar,

In my opinion we have to measure the time we take to deliver customer
service and from what I understand you are marking the time of the
technician.
But anyway thanks for the quick reply.


Sds

Pablo Horta
27-99291.4489


Em ter, 23 de jul de 2019 às 03:15, Oscar B. <notifications@github.com>
escreveu:
