### ISSUE TITLE
Modelo de Chamado > Campo predefinido > Tarefa

### ISSUE THREAD

**Issue by nadsonpaulo** [ticgal/actualtime#84]
<p><a href="https://github.com/ticgal/actualtime/issues/84">https://github.com/ticgal/actualtime/issues/84</a></p><p>Senhores, bom dia.</p><p>Gostaria de sugerir que o contador de tempo fosse ativado na criação da tarefa predefinida do chamado. Quando isso é feito em um modelo de chamado o contador não é ativado, apenas se for inserido manualmente pelo técnico.</p><ol><li><p>Tarefa inserida no "Modelo de Chamado" <img src="https://user-images.githubusercontent.com/29984070/109161552-f5852000-7755-11eb-9335-e3a1a467f8d4.png" alt="tela1" /> <img src="https://user-images.githubusercontent.com/29984070/109161734-2e24f980-7756-11eb-90a0-cf61e3e192ce.png" alt="tela2" /></p></li><li><p>Tarefa inserida manualmente. <img src="https://user-images.githubusercontent.com/29984070/109162168-aa1f4180-7756-11eb-97be-18454c6e5d8f.png" alt="tela3" /></p></li><li><p>Diferença das duas Tarefas inseridas de formas diferentes. <img src="https://user-images.githubusercontent.com/29984070/109162402-ee124680-7756-11eb-899e-d50e7ff3b5db.png" alt="tela4" /></p></li></ol><p><br />Creado por nadsonpaulo</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_5202' rel='nofollow'>5202</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by OscarBeiro** [comment]
Bom dia Paulo,

I'm answering in English. 
There's no real issue with Ticket Templates, but a misconception from your side. 

Actualtime is not added to tasks. It is simply shown **when the ticket tech is the same as the logged user**.

Imagine I'm your tech. And you assign me a ticket task. I can start, pause and stop it, but you cannot. 

The real issue behind your problem is that the template doesn't have a tech. So, once you use a template, you have to make the tech assignment or create a template for each tech, which could be overkill in organizations with many techs.

We could discuss if the big picture used by GLPI should be for the assigned tech, instead of the task creator, but this is something it must be dealt with on the GLPI repository.

Obrigado por utilisar o Actualtime :)
Até ja
